version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: default
      POSTGRES_USER: user
      POSTGRES_DB: unleash
    ports:
      - "5432:5432"
    networks:
      - unleash
    container_name: postgres

  unleash:
    image: unleashorg/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: unleash
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: default
      DATABASE_SSL: "false"
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
    networks:
      - unleash
    depends_on:
      - postgres
    container_name: unleash-server

  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
  unleash:
